### PR TITLE
First file

### PR DESCRIPTION
**Pull request by sshenis**
Sep 10, 2019 Week 1

### CODE REVIEW

**Comment by sshenis** [comment]
irvin accept me pls

**Comment by Peeterlee** [comment]
denied

**Comment by jjanicefong** [comment]
yay

**Comment by sshenis** [comment]
i hate u all pls help ),:

**Comment by irvinalcira** [comment]
this is god awful

**Comment by sshenis** [comment]
irvin kys

**Comment by josephbondoc** [comment]
omg THIS IS SO BAD!!!! WHO HIRED YOU!!!!!!

**Comment by josephbondoc** [comment]
IMG_9976

**Pull request merged**
